# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'newsMailer.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDialog, QHeaderView,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QTableWidget, QTableWidgetItem, QWidget)

class Ui_dlgMain(object):
    def setupUi(self, dlgMain):
        if not dlgMain.objectName():
            dlgMain.setObjectName(u"dlgMain")
        dlgMain.resize(674, 551)
        self.leNewID = QLineEdit(dlgMain)
        self.leNewID.setObjectName(u"leNewID")
        self.leNewID.setGeometry(QRect(350, 100, 51, 20))
        font = QFont()
        font.setPointSize(10)
        self.leNewID.setFont(font)
        self.cbSend = QCheckBox(dlgMain)
        self.cbSend.setObjectName(u"cbSend")
        self.cbSend.setGeometry(QRect(430, 98, 221, 21))
        font1 = QFont()
        font1.setPointSize(11)
        self.cbSend.setFont(font1)
        self.leSearch = QLineEdit(dlgMain)
        self.leSearch.setObjectName(u"leSearch")
        self.leSearch.setGeometry(QRect(350, 150, 301, 20))
        self.leSearch.setFont(font)
        self.pbNew = QPushButton(dlgMain)
        self.pbNew.setObjectName(u"pbNew")
        self.pbNew.setGeometry(QRect(350, 190, 51, 41))
        self.pbNew.setFont(font1)
        self.pbEdit = QPushButton(dlgMain)
        self.pbEdit.setObjectName(u"pbEdit")
        self.pbEdit.setGeometry(QRect(410, 190, 51, 41))
        self.pbEdit.setFont(font1)
        self.pbDelete = QPushButton(dlgMain)
        self.pbDelete.setObjectName(u"pbDelete")
        self.pbDelete.setGeometry(QRect(470, 190, 51, 41))
        self.pbDelete.setFont(font1)
        self.leEmailID = QLineEdit(dlgMain)
        self.leEmailID.setObjectName(u"leEmailID")
        self.leEmailID.setGeometry(QRect(350, 300, 51, 20))
        self.leEmailID.setFont(font)
        self.leEmail = QLineEdit(dlgMain)
        self.leEmail.setObjectName(u"leEmail")
        self.leEmail.setGeometry(QRect(350, 340, 281, 20))
        self.leEmail.setFont(font)
        self.leName = QLineEdit(dlgMain)
        self.leName.setObjectName(u"leName")
        self.leName.setGeometry(QRect(430, 300, 201, 20))
        self.leName.setFont(font)
        self.leMemo = QLineEdit(dlgMain)
        self.leMemo.setObjectName(u"leMemo")
        self.leMemo.setGeometry(QRect(350, 380, 281, 20))
        self.leMemo.setFont(font)
        self.leSTime = QLineEdit(dlgMain)
        self.leSTime.setObjectName(u"leSTime")
        self.leSTime.setGeometry(QRect(70, 510, 113, 20))
        self.leSTime.setFont(font)
        self.label = QLabel(dlgMain)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 121, 21))
        font2 = QFont()
        font2.setPointSize(12)
        self.label.setFont(font2)
        self.label_2 = QLabel(dlgMain)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 250, 121, 21))
        self.label_2.setFont(font2)
        self.label_3 = QLabel(dlgMain)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(350, 80, 121, 21))
        self.label_3.setFont(font2)
        self.label_4 = QLabel(dlgMain)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(350, 130, 121, 21))
        self.label_4.setFont(font2)
        self.label_5 = QLabel(dlgMain)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(350, 280, 121, 21))
        self.label_5.setFont(font2)
        self.label_6 = QLabel(dlgMain)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(430, 280, 121, 21))
        self.label_6.setFont(font2)
        self.label_7 = QLabel(dlgMain)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(350, 320, 121, 21))
        self.label_7.setFont(font2)
        self.label_8 = QLabel(dlgMain)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(350, 360, 121, 21))
        self.label_8.setFont(font2)
        self.label_9 = QLabel(dlgMain)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(70, 490, 121, 21))
        self.label_9.setFont(font2)
        self.pbSaveTime = QPushButton(dlgMain)
        self.pbSaveTime.setObjectName(u"pbSaveTime")
        self.pbSaveTime.setGeometry(QRect(200, 500, 71, 31))
        self.pbSaveTime.setFont(font1)
        self.pbSave = QPushButton(dlgMain)
        self.pbSave.setObjectName(u"pbSave")
        self.pbSave.setGeometry(QRect(530, 190, 51, 41))
        self.pbSave.setFont(font1)
        self.pbCancel = QPushButton(dlgMain)
        self.pbCancel.setObjectName(u"pbCancel")
        self.pbCancel.setGeometry(QRect(590, 190, 51, 41))
        self.pbCancel.setFont(font1)
        self.pbEditEmail = QPushButton(dlgMain)
        self.pbEditEmail.setObjectName(u"pbEditEmail")
        self.pbEditEmail.setGeometry(QRect(410, 420, 51, 41))
        self.pbEditEmail.setFont(font1)
        self.pbSaveEmail = QPushButton(dlgMain)
        self.pbSaveEmail.setObjectName(u"pbSaveEmail")
        self.pbSaveEmail.setGeometry(QRect(530, 420, 51, 41))
        self.pbSaveEmail.setFont(font1)
        self.pbNewEmail = QPushButton(dlgMain)
        self.pbNewEmail.setObjectName(u"pbNewEmail")
        self.pbNewEmail.setGeometry(QRect(350, 420, 51, 41))
        self.pbNewEmail.setFont(font1)
        self.pbCancelEmail = QPushButton(dlgMain)
        self.pbCancelEmail.setObjectName(u"pbCancelEmail")
        self.pbCancelEmail.setGeometry(QRect(590, 420, 51, 41))
        self.pbCancelEmail.setFont(font1)
        self.pbDeleteEmail = QPushButton(dlgMain)
        self.pbDeleteEmail.setObjectName(u"pbDeleteEmail")
        self.pbDeleteEmail.setGeometry(QRect(470, 420, 51, 41))
        self.pbDeleteEmail.setFont(font1)
        self.tblNews = QTableWidget(dlgMain)
        self.tblNews.setObjectName(u"tblNews")
        self.tblNews.setGeometry(QRect(20, 40, 311, 201))
        self.tblEmail = QTableWidget(dlgMain)
        self.tblEmail.setObjectName(u"tblEmail")
        self.tblEmail.setGeometry(QRect(20, 280, 311, 201))

        self.retranslateUi(dlgMain)

        QMetaObject.connectSlotsByName(dlgMain)
    # setupUi

    def retranslateUi(self, dlgMain):
        dlgMain.setWindowTitle(QCoreApplication.translate("dlgMain", u"\uc790\ub3d9 \ub274\uc2a4 \uc774\uba54\uc77c\ub7ec", None))
        self.cbSend.setText(QCoreApplication.translate("dlgMain", u"Check it! if you want to send email", None))
        self.pbNew.setText(QCoreApplication.translate("dlgMain", u"New", None))
        self.pbEdit.setText(QCoreApplication.translate("dlgMain", u"Edit", None))
        self.pbDelete.setText(QCoreApplication.translate("dlgMain", u"Del", None))
        self.leSTime.setInputMask("")
        self.label.setText(QCoreApplication.translate("dlgMain", u"Search Keyword", None))
        self.label_2.setText(QCoreApplication.translate("dlgMain", u"Email Address", None))
        self.label_3.setText(QCoreApplication.translate("dlgMain", u"ID", None))
        self.label_4.setText(QCoreApplication.translate("dlgMain", u"Keyword", None))
        self.label_5.setText(QCoreApplication.translate("dlgMain", u"ID", None))
        self.label_6.setText(QCoreApplication.translate("dlgMain", u"Name", None))
        self.label_7.setText(QCoreApplication.translate("dlgMain", u"Email", None))
        self.label_8.setText(QCoreApplication.translate("dlgMain", u"Memo", None))
        self.label_9.setText(QCoreApplication.translate("dlgMain", u"Send Time", None))
        self.pbSaveTime.setText(QCoreApplication.translate("dlgMain", u"Save", None))
        self.pbSave.setText(QCoreApplication.translate("dlgMain", u"Save", None))
        self.pbCancel.setText(QCoreApplication.translate("dlgMain", u"Cancel", None))
        self.pbEditEmail.setText(QCoreApplication.translate("dlgMain", u"Edit", None))
        self.pbSaveEmail.setText(QCoreApplication.translate("dlgMain", u"Save", None))
        self.pbNewEmail.setText(QCoreApplication.translate("dlgMain", u"New", None))
        self.pbCancelEmail.setText(QCoreApplication.translate("dlgMain", u"Cancel", None))
        self.pbDeleteEmail.setText(QCoreApplication.translate("dlgMain", u"Del", None))
    # retranslateUi

